name = "DataTrees"
uuid = "98431770-4ef7-4c08-ae31-e12f64579c2a"
authors = ["Sam Aucoin"]
version = "1.0.0-DEV"

[compat]
julia = "1.10.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
